### ISSUE TITLE
High priority order scenarios

### ISSUE THREAD

**Issue by AravindaDP** [usnistgov/ARIAC#182]
Please clarify if following assumptions are correct.

1. order_0 will be always a regular order. (i.e. no scenario where a regular order announcement after a high priority order)
2. There can be at most only one order apart from order_0
3. This can be named either as order_0_update or order_1
4. We are to assume these are of priority 3 and process accordingly. (Simply because there is no flag on announced order message indicating priority?) (Note that in trial config still can define both order_0 and order_1 as regular orders and order_1 is announced only after order_0 is submitted. However in this case there is no behavior change treating order_1 as high priority since order_0 is anyway completed)
5. In case order_0_update, It will use same set of agv, moveable_tray etc.

Do we need to handle following scenarios as well?
A. order_0 and hence order_0_update contains multiple kitting or assembly shipments? (But update is triggered before any shipment is to be completed)
B. will order_0_update scenario is used with assembly only shipment as well? (Needing removing/rearranging already assembled parts. We recon that removing/rearranging parts from kit trays as part of kitting shipment is required scenario that we need to handle)

**Comment by zeidk** [comment]
You are absolutely correct on everything described here. There is no flag to tell the priority of an order and you will need to always consider order_1 and order_0_update as orders to complete "right away", regardless whether they are high-priority orders or  regular orders (announced after order_0 has been completed).

order_0_update scenarios, if present, will only be for kitting. It cannot be present in assembly since parts automatically lock in the briefcase during scenario and cannot be removed.
