### ISSUE TITLE
shipment

### ISSUE THREAD

**Issue by liuhaoran1** [usnistgov/ARIAC#196]
In ariac 2023, is there still shipment? Is there more than one shipment in one order? Whether only one of the tasks of the kitting task,assembly task or combined task will appear in an order？

**Comment by jaybrecht** [comment]
For ARIAC2023 we have modified it so that there is only one task or "shipment" for each order. Each order will have a single task and the type of task will be specified by the field "type".

Here is the Order.msg for reference.
```
uint8 KITTING=0
uint8 ASSEMBLY=1
uint8 COMBINED=2

string id
uint8 type
bool priority
ariac_msgs/KittingTask kitting_task 
ariac_msgs/AssemblyTask assembly_task
ariac_msgs/CombinedTask combined_task
```

For example, if an order has an type of ASSEMBLY (1) then the "assembly_task" field will have the necessary info for that order. The kitting_task and combined_task fields would be left empty.
