### ISSUE TITLE
grab pumps

### ISSUE THREAD

**Issue by LKmubihei** [usnistgov/ARIAC#220]
I find a bug in picking up objects. When grabbing pump parts, even if I'm extremely careful and slow, it causes the pump to wobble in the gripper and makes it impossible to successfully pick up. I occasionally succeed in picking it up in my code, but it has never been successfully picked up in the sample code.

**Comment by LKmubihei** [comment]
time_limit: -1 # options: -1 (no time limit) or number of seconds (max 500)

kitting_trays: # Which kitting trays will be spawn
  tray_ids: [3, 8] 
  slots: [1, 4]

parts:
  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin5:
      - type: 'pump'
        color: 'blue'
        slots: [1, 3,7,9]
    bin6:
      - type: 'battery'
        color: 'red'
        slots: [1, 3, 7, 9]
        flipped: true
    bin2:
      - type: 'regulator'
        color: 'blue'
        slots: [1, 4]
        flipped: true
      - type: 'sensor'
        color: 'blue'
        slots: [5,7]
        flipped: true

orders:
  - id: 'MMB30H56'
    type: 'kitting'
    announcement:
      time_condition: 0
    priority: false
    kitting_task:
      agv_number: 4
      tray_id: 3
      destination: 'warehouse'
      products:
        - type: 'battery'
          color: 'red'
          quadrant: 2
        - type: 'pump'
          color: 'blue'
          quadrant: 1
        - type: 'pump'
          color: 'blue'
          quadrant: 3

This is my test trial

**Comment by jaybrecht** [comment]
The test_competitor was not designed to pick up flipped parts since that is one of the ARIAC challenges. It is expected that it will fail in this case. If you are getting the pose info for a part from the logical camera then you should check to see if it is flipped before picking it up.

without flipped parts the test_competitor was able to pick up the pumps for the trial you listed. 
https://user-images.githubusercontent.com/50928580/230385229-7dc1a665-ed9f-4b1c-90c6-8552df5260ba.mp4
