### ISSUE TITLE
attaching a part with two robots causes explosion

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#330]
When working on flipped parts and using the illustrated technique of having the two robots do a hand-off of the part, when the part is attached by the second robot, the entire sim immediately explodes most of the time.

**Comment by dan9thsense** [comment]
The pump is the worst. The others survive about half the time, but the pump causes the sim to explode every time.

**Comment by jaybrecht** [comment]
Are you turning off the gripper of the first robot before turning on the gripper of the other?

**Comment by dan9thsense** [comment]
If I do that, the part falls off.  Then I tried putting the gripper facing upwards so that the part would balance on it momentarily, but the gripper has an inherent vibration that causes the part to drift from the center and fall off.  So it seems that they both need to be gripping for a short time.  In a previous year, I was able to do this with both grippers on momentarily, but not this year.

It may be possible to time things just right so that the first gripper releases right before the second one attaches, but that is the opposite of agile-- it is about as fragile as a kludge gets.  A tiny bit of timing glitch and it will fail.  Also, that lack of positive control of a part would never be allowed on a factory floor.

**Comment by Sanchitkedia** [comment]
When transferring the part from one robot to another, are you updating the planning scene?

**Comment by dan9thsense** [comment]
No, I didn't do that.  Why would that help with the explosion?  And when would I do that?  Sometime before the second one attaches?

**Comment by Sanchitkedia** [comment]
I tried implementing the method I used last year. It works, but sometimes, the parts don't transfer and slide off. I am not using the "CeilingRobotWaitForAttach" function, hence the slide. I was able to replicate the explosion you are referring to when using the "CeilingRobotWaitForAttach" function. Please feel free to disregard the planning scene part.

**Comment by Sanchitkedia** [comment]
https://github.com/usnistgov/ARIAC/assets/61658557/f80fc9ab-0a4b-4fa8-a7a1-6da02f7db654

Process :

- The floor robot positions itself in the handoff position
- Detach the object from the floor robot(planning interface) and remove it from the planning scene.
- The ceiling robot approaches the part slowly, only up to the part surface.
- The gripper of the floor robot remains active, and the ceiling robot's gripper is activated.
    - I don't check if contact has been made, i.e., I don't check if gripper_state_.attached is true; hence, the part sometimes slips.
- Deactivate the floor robot's gripper.
- The part is re-added to the planning scene.
- The ceiling robot places the part in the appropriate quadrant.

p.s.  It can be improved by checking to ensure the gripper topic reports "true."

**Comment by dan9thsense** [comment]
@Sanchitkedia  Thank you for the detailed reply; that is very considerate.  I think the key here is that you deactivate the floor gripper before checking that contact and attachment has been made by the ceiling gripper.  If it is slipping, that means the floor deactivated before the ceiling attached.  In those cases, my code works too.  However, this is not a way that works in the real world.  On the factory floor, safety concerns do not allow losing positive control of the part like that.  Also, the explosion is just a sim artifact.  In the real world, robot arms have enough compliance to allow momentary attachment of two arms simultaneously.

**Comment by jaybrecht** [comment]
Yes, I agree Dan. I think this is unfortunately another issue where the gazebo simulation environment has limitations that prevent real world solutions. The way our "vacuum gripper" works is by directly creating a joint between the robot and the part. Also the robots share a robot descriptions so are technically one robot model. Therefore when you try to pick the part using the other robot the robots are fixed together in two places (the world frame and the part frame). I guess the simulation really doesn't like that. 

I know time is limited but it might be worth looking into handling the flip part challenge using a single robot by placing the part on it's side on the AGV and re-picking to flip. This might be more repeatable. 

However, since the issue does not occur every time the fact that trials are run multiple times and we take the best run of the bunch that should prevent the inconsistency from hindering your score too much.

**Comment by dan9thsense** [comment]
Good points. I can make it work well enough. Thanks for looking into it.
