### ISSUE TITLE
did qual_a_3 change?

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#54]
Pulled from the repo today.  Looks like qual_a_3 has changed from when it was originally released, with the gear part blue in bin3 moved to shelf 8 and replaced with a pulley part red.  Is that right?
If the qual_a trials are part of the scoring, this sort of change makes things really hard for teams that submitted earlier in the quals window and do not happen to have time this week to make and then test code changes.

**Comment by zeidk** [comment]
Hi Dan, I believe there was a mistake in qual_a_3 that we had to fix.
I saw that you also posted in another thread about your frustration and I completely understand the state of mind. 
For the time being,  I can definitely test the code you submitted (grabbed from build_team_system.bash) with the version of the qualifier files and the version of ARIAC you used. There are only a few changes we made since you uploaded your files and we can get the version of ARIAC you used. I will also create a docker image locally for your version. If you are afraid that you won't make it through the qualifiers because of the situation I can send you an email to discuss it.

**Comment by dan9thsense** [comment]
Thanks for reading the long rant in the other thread (Could have been classified TL;DR).  I also understand that it's hard to develop code for these competitions.  And I do very much appreciate how responsive you have been to the issues submitted.  I don't expect or want any special consideration; the code should stand or fall on its own-- I did test with the new docker images and while it gets a lower score than before, at least it doesn't crash!  Overall, things are OK, I just wanted to make the point that late changes can be pretty painful to developers who have invested a lot of time getting the original scenarios to work well.

**Comment by zeidk** [comment]
I completely understand your point of view for changing things after people have submitted their code. Although they were fixes that had to be done I agree with everything you said. I have to make angry customers on both sides happy and I'm trying my best :) 

There were only 2 teams who submitted their code before the changes and I felt confident that I could take care of these two cases separately if needed (just like I proposed in my previous reply). 

Thanks for your understanding and your patience :)
