### ISSUE TITLE
All contacts go active once any part moves

### ISSUE THREAD

**Issue by stevegray954** [usnistgov/ARIAC#6]
Check out this video of moving a gear:
https://www.youtube.com/watch?v=d4r4zSL8EOg&feature=youtu.be

All the other contacts on all other objects activate.  This shouldn't happen.  Unfortunately, it's likely a gazebo bug.  Any time a part moves, all contacts go active.  This does not happen when the robot moves.

Easy to replicate - turn on contact visualization and move anything.

Edit: Note, this video has my fix from #4 present, which is why it only slows to 0.72x instead of 0.12x on my machine.  This issue was present before and after that other fix.

**Comment by stevegray954** [comment]
I can replicate this issue with just plain Gazebo 9.12 by adding two boxes and looking at contacts when I move one box.  All contacts go active; this is a Gazebo issue and not an ARIAC specific issue.

**Comment by Pavel-P** [comment]
I've ran into this issue in the past-- however I think it only happens when manually changing the locations of parts in the GUI. Interacting with parts using the robot or conveyor should never result in contacts re-activating for all parts, in my experience. Let me know if you run into this issue while running the competition (with `moveit_example.py` for example) and I'll take another look at it.
